workflow:
  auto_cancel:
    on_new_commit: conservative

variables:
  GIT_DEPTH: 0 # Disable shallow clone, so git-describe works for our version detection

default:
  image: oven/bun:1.3.5-alpine
  cache: &global-cache
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules

stages:
  - setup
  - test
  - build
  - dockerize
  - deploy

setup:
  stage: setup
  interruptible: true
  script: bun ci
  cache:
    <<: *global-cache
    policy: push

lint:
  stage: test
  interruptible: true
  script:
    - bun ci
    - bun run lint
  cache:
    <<: *global-cache
    policy: pull

test:
  stage: test
  interruptible: true
  script:
    - bun ci
    - bun test
  cache:
    <<: *global-cache
    policy: pull

# Does not work, no priority to get it running ;-)
# Issue is an IPv4/v6 problem on the GitLab runner: When quickly logging into the running docker container,
# installing curl, and running different commands, you'll see:
# "curl -4 http://localhost:4173" fails, "curl -6 http://localhost:4173" works.
# I tried different approaches waiting on "[::1]" or "ip6-localhost", neither worked :-(
#cypress:
#  stage: test
#  interruptible: true
#  script:
#    - bun ci
#    - bun test:e2e
#  cache: []
#  artifacts:
#    when: always
#    paths:
#      - cypress/screenshots/*

build:
  stage: build
  interruptible: true
  before_script: apk add git # install Git for git-describe
  script:
    - bun ci
    - bun run build
  cache:
    <<: *global-cache
    policy: pull
  artifacts:
    paths:
      - dist/

dockerize:
  stage: dockerize
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^feature\/.+$/
  dependencies:
    - build
  tags:
    - docker-daemon
  cache: []
  script: |
    DOCKER_TAG="${CI_COMMIT_TAG#v}"
    DOCKER_TAG="${DOCKER_TAG:-latest}"
    echo "Building docker tag '${DOCKER_TAG}'..."
    echo "DOCKER_TAG=${DOCKER_TAG}" > docker-tag.env
    
    echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    docker build -t "$CI_REGISTRY/th-wiki/th-wiki-ui:$DOCKER_TAG" .
    docker push "$CI_REGISTRY/th-wiki/th-wiki-ui:$DOCKER_TAG"
  artifacts:
    reports:
      dotenv: docker-tag.env

deploy-test:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^feature\/.+$/
  image: alpine:3.20.2
  script: |
    if [ -z "$DOCKER_TAG" ]; then
      echo "Error: DOCKER_TAG is not defined. Previous dockerize step should have set that."
      exit 1
    fi
    echo "Deploying docker image version '${DOCKER_TAG}'..."
    
    apk add openssh
    mkdir -p ~/.ssh
    cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    chmod 600 "$SSH_PRIVATE_KEY"
    
    ssh -i "$SSH_PRIVATE_KEY" "$SSH_LOGIN" sh -s <<SSHCOMMANDS
      cd $DOCKER_DIRECTORY_TEST && \
      sed -i 's|\(image: '"${CI_REGISTRY}"'/th-wiki/th-wiki-ui:\).*|\1'"${DOCKER_TAG}"'|' docker-compose.yml && \
      docker compose pull && \
      docker compose up -d
    SSHCOMMANDS
  cache: []

deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  image: alpine:3.20.2
  script: |
    if [ -z "$DOCKER_TAG" ]; then
      echo "Error: DOCKER_TAG is not defined. Previous dockerize step should have set that."
      exit 1
    fi
    echo "Deploying docker image version '${DOCKER_TAG}'..."
    
    apk add openssh
    mkdir -p ~/.ssh
    cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    chmod 600 "$SSH_PRIVATE_KEY"
    
    ssh -i "$SSH_PRIVATE_KEY" "$SSH_LOGIN" sh -s <<SSHCOMMANDS
      cd $DOCKER_DIRECTORY_PROD && \
      sed -i 's|\(image: '"${CI_REGISTRY}"'/th-wiki/th-wiki-ui:\).*|\1'"${DOCKER_TAG}"'|' docker-compose.yml && \
      docker compose pull && \
      docker compose up -d
    SSHCOMMANDS
  cache: []
  when: manual
